# Generated by Django 5.2 on 2025-04-23 09:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('credit', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('syllabus', models.FileField(upload_to='syllabus/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='profiles.facultyprofile')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='dependent_courses', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('feedback', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_feedback', to='profiles.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProposedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('credit', models.IntegerField(default=1)),
                ('syllabus', models.FileField(upload_to='syllabus/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('is_deleted', models.BooleanField(default=False)),
                ('course', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_courses', to='profiles.facultyprofile')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='proposed_dependent_courses', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, choices=[('O', 'Outstanding'), ('A+', 'Excellent'), ('A', 'Very Good'), ('B+', 'Good'), ('B', 'Average'), ('C', 'Below Average'), ('D', 'Pass'), ('F', 'Fail')], max_length=2, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='profiles.studentprofile')),
            ],
            options={
                'unique_together': {('course', 'student')},
            },
        ),
    ]
